<a href="https://colab.research.google.com/github/donisrv/Data-Science-ML-AI/blob/main/Boolean_Indekslash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

2.1.1. N-o'lchamli massiv (array)larga ishlov berish
Bolean Indekslash

In [5]:
import numpy as np

In [ ]:
# Ismlar
names = np.array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Jovohir', 'Elyor'])
names

array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Jovohir', 'Elyor'],
      dtype='<U8')

In [ ]:
# data
data = np.random.randn(7, 4)
data

array([[-1.18601969, -1.14740263,  0.53377754, -0.30520187],
       [ 0.25769257,  0.55312029, -0.29209895,  0.98997317],
       [ 0.41172316, -0.59544489, -0.61564884, -0.87155024],
       [ 2.51449607, -0.17165775, -1.76408877, -0.28315504],
       [ 1.48922345, -0.47285845,  0.36850894, -0.3008245 ],
       [ 1.24347061, -0.0076268 , -1.22069823,  1.06990967],
       [ 0.4735319 ,  0.42147782,  0.64673209, -1.34518651]])

In [ ]:
names == 'Hasan'

array([ True, False, False, False,  True, False, False])

In [ ]:
data[names == 'Hasan'] # Hasanga tegishli barcha ma'lumotlarni ajratib olish

array([[-1.18601969, -1.14740263,  0.53377754, -0.30520187],
       [ 1.48922345, -0.47285845,  0.36850894, -0.3008245 ]])

In [ ]:
data[names == 'Elyor'] # Elyorga tegishli barcha ma'lumotlarni ajratib olish

array([[ 2.51449607, -0.17165775, -1.76408877, -0.28315504],
       [ 0.4735319 ,  0.42147782,  0.64673209, -1.34518651]])

In [ ]:
data[names == 'Husan'] # Husanga tegishli barcha ma'lumotlarni ajratib olish

array([[-0.11854623, -0.63809246, -0.61989623, -0.76427123]])

In [ ]:
data[names=='Hasan', 2:] # Hasanga tegishli oxirgi ikkita ustundagi ma'lumotlarni ajratib olish

array([[-0.764806  ,  0.56642411],
       [-0.80341514,  0.2270759 ]])

In [ ]:
data[names=='Husan', :2] # Husanga tegishli oxirgi ikkita ustundagi ma'lumotlarni ajratib olish

array([[-0.11854623, -0.63809246]])

In [ ]:
data[names != 'Hasan'] # (!=)Hasandan tashqari barcha insonlarning ma'lumotlarni ajratib olish

array([[-0.11854623, -0.63809246, -0.61989623, -0.76427123],
       [-1.04283845, -1.958119  ,  1.60295445, -0.88350431],
       [-0.75877684, -1.70240591,  1.5050407 ,  1.16670549],
       [-2.96612522,  0.57880335, -0.54526737,  0.0249023 ],
       [-0.39899929, -0.60943313,  0.58889664, -0.138976  ]])

In [ ]:
data[~(names == 'Hasan')] # (~) yuqoridagi cell bilan bir xil natijani berar ekan

array([[-0.11854623, -0.63809246, -0.61989623, -0.76427123],
       [-1.04283845, -1.958119  ,  1.60295445, -0.88350431],
       [-0.75877684, -1.70240591,  1.5050407 ,  1.16670549],
       [-2.96612522,  0.57880335, -0.54526737,  0.0249023 ],
       [-0.39899929, -0.60943313,  0.58889664, -0.138976  ]])

In [ ]:
print(names)
print(data)

['Hasan' 'Husan' 'Mirzabek' 'Elyor' 'Hasan' 'Jovohir' 'Elyor']
[[ 1.11125281 -0.12096374 -0.764806    0.56642411]
 [-0.11854623 -0.63809246 -0.61989623 -0.76427123]
 [-1.04283845 -1.958119    1.60295445 -0.88350431]
 [-0.75877684 -1.70240591  1.5050407   1.16670549]
 [ 0.06667806  0.92211753 -0.80341514  0.2270759 ]
 [-2.96612522  0.57880335 -0.54526737  0.0249023 ]
 [-0.39899929 -0.60943313  0.58889664 -0.138976  ]]


In [ ]:
mask = (names == 'Hasan') | (names == 'Husan') # "|" or (yoki)
mask #  Husan va Hasanga tegishli oxirgi ikkita ustundagi ma'lumotlarni ajratib olish

array([ True,  True, False, False,  True, False, False])

In [ ]:
data[mask] # Hasan va Husanlarga tegishli ma'lumotlarni ajratib olish

array([[ 1.11125281, -0.12096374, -0.764806  ,  0.56642411],
       [-0.11854623, -0.63809246, -0.61989623, -0.76427123],
       [ 0.06667806,  0.92211753, -0.80341514,  0.2270759 ]])

In [ ]:
data

array([[ 1.11125281, -0.12096374, -0.764806  ,  0.56642411],
       [-0.11854623, -0.63809246, -0.61989623, -0.76427123],
       [-1.04283845, -1.958119  ,  1.60295445, -0.88350431],
       [-0.75877684, -1.70240591,  1.5050407 ,  1.16670549],
       [ 0.06667806,  0.92211753, -0.80341514,  0.2270759 ],
       [-2.96612522,  0.57880335, -0.54526737,  0.0249023 ],
       [-0.39899929, -0.60943313,  0.58889664, -0.138976  ]])

In [ ]:
data[data<0] = 0
data

array([[1.11125281, 0.        , 0.        , 0.56642411],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.60295445, 0.        ],
       [0.        , 0.        , 1.5050407 , 1.16670549],
       [0.06667806, 0.92211753, 0.        , 0.2270759 ],
       [0.        , 0.57880335, 0.        , 0.0249023 ],
       [0.        , 0.        , 0.58889664, 0.        ]])

# ![Imgur](https://i.imgur.com/5pXzCIu.png)

# **DATA SCIENCE VA SUN'IY INTELLEKT PRAKTIKUM**

## Ma'lumotlar tahlili. Numpy kutubxonasi. 

# **2-AMALIY VAZIFA**

## N-o'lchamli massivlarga ishov berish

### Masala(1): 2-o'lchamli massiv yaratish 

**Masala sharti :** Elementlari 0 dan 9 gacha (9 ning o'zi massiv elementiga kirmaydi), qadami esa 1 ga teng bo'lgan (3, 3) o'lchamli massiv yaratuvchi funksiyani davom ettiring.  

**Yordam :**  `arange`dan foydalanish ishni osonlashtiradi 


In [3]:
# JAVOBNI SHU YERGA YOZING
def nd_array():
  """Elementlari 0 dan 9 gacha (9 ning o'zi massiv elementiga kirmaydi), 
  qadami esa 1 ga teng bo'lgan (3, 3) o'lchamli massiv """
  arrn = np.arange(9).reshape(3, 3)
  print("""Elementlari 0 dan 9 gacha (9 ning o'zi massiv elementiga kirmaydi), 
  qadami esa 1 ga teng bo'lgan (3, 3) o'lchamli massiv \n""",arrn)
  return arrn

Tekshirish (natijada hech qanday xatolik yuz bermasligi kerak)


In [6]:
#@title Tekshirish (natijada hech qanday xatolik yuz bermasligi kerak)
"""Funksiyani tekshirish"""
arr = nd_array() # massiv
assert arr.size == 9, f"elementlar sonida xatolik mavjud"  # elementlar soni
assert type(arr) == np.ndarray, f"massiv aniqlanmadi" #numpy array 
# elementwise test
test_arr = np.arange(9).reshape(3, 3)
assert arr.shape == (3, 3), f"noto'g'ri qator va ustunlardan foydalanilgan"
assert True in np.in1d(arr, test_arr), f"elementlararo xatolik mavjud"


Elementlari 0 dan 9 gacha (9 ning o'zi massiv elementiga kirmaydi), 
  qadami esa 1 ga teng bo'lgan (3, 3) o'lchamli massiv 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


###  Masala(2): Indeks yordamida 2-o'lchamli massivlardan elementlarni  kesib olish 
**Masala :** Yuqorida yaratilgan massivning elementlari 6 va 7 ga teng bo'lgan qismini kesib olish funksiyasini davom ettiring.

**Yordam :** 6 va 7 turgan indekslarni aniqlab olib, shu indekslar yordamida kesib oling. **Natija:** array([6, 7]) ko'rinishida bo'lishi kerak. 

In [11]:
# JAVOBNI SHU YERGA YOZING
def sliced_array_2d():
    """Yuqorida yaratilgan massivning elementlari 6 va 7 ga teng bo'lgan
     qismini kesib olish funksiyasi """
    array = nd_array() # yuqoridagi funksiya yordamida array yaratib olish
    arn = array[2, :2]
    print("""\nYuqorida yaratilgan massivning elementlari 6 va 7 ga teng bo'lgan
     qismini kesib olish funksiyasi """)
    print("")
    print('Javob:',arn)
    return arn

In [12]:
#@title Tekshirish (natijada hech qanday xatolik yuz bermasligi kerak)
"""Funksiyani tekshirish"""
sl_arr_2d = sliced_array_2d() # kesib olingan massiv
assert sl_arr_2d.size == 2, f"elementlar sonida xatolik mavjud"  # elementlar soni
assert type(sl_arr_2d) == np.ndarray, f"massiv aniqlanmadi" #numpy array 
# elementwise test
test_arr = np.array([6, 7])
assert sl_arr_2d.shape == (2,), f"kesib olingan massiv shaklida xatolik mavjud"
assert True in np.in1d(sl_arr_2d, test_arr), f"elementlararo xatolik mavjud"

Elementlari 0 dan 9 gacha (9 ning o'zi massiv elementiga kirmaydi), 
  qadami esa 1 ga teng bo'lgan (3, 3) o'lchamli massiv 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Yuqorida yaratilgan massivning elementlari 6 va 7 ga teng bo'lgan
     qismini kesib olish funksiyasi 

Javob: [6 7]
