<a href="https://colab.research.google.com/github/donisrv/Data-Science-ML-AI/blob/main/Ma'lumotlar_turi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Numpy kutubxonasini chaqirib olish
import numpy as np

In [5]:
arr1 = np.array([1, 2, 3, 4], dtype = np.float64) # bu int64 ma'lumotlar turiga ega massiv
arr1

array([1., 2., 3., 4.])

In [6]:
arr2 = np.array([1, 2, 3, 4], dtype = np.int32) # bu int32 ma'lumotlar turiga ega massiv
arr2

array([1, 2, 3, 4], dtype=int32)

`dtype` metodi

In [7]:
arr1.dtype

dtype('float64')

In [8]:
arr2.dtype

dtype('int32')

Bir turdagi ma'lumot turidan boshqasiga o'girish

In [9]:
arr = np.array([1, 2, 3, 4]) # int64
arr

array([1, 2, 3, 4])

In [10]:
arr.dtype

dtype('int64')

In [11]:
float_arr = arr.astype(np.float64) # float_arr ga arr ni float64 ga ogirib biriktirib qoyyapmiz
float_arr.dtype

dtype('float64')

In [12]:
data = np.array([3.4, 5.7, 1.8, 4]) # float64
data.dtype

dtype('float64')

In [13]:
int_data = data.astype(np.int64)
int_data.dtype

dtype('int64')