<a href="https://colab.research.google.com/github/donisrv/Data-Science-ML-AI/blob/main/NumPy_kutubxonasi_N_o'lchamli_massivlar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
data4 = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [4]:
data4

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [5]:
data4.ndim

AttributeError: ignored

In [7]:
array_3d = np.zeros((3, 4, 2))

In [8]:
print(array_3d)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [9]:
array_3d1 = np.random.rand(3, 4, 2)

In [10]:
print(array_3d1)

[[[0.46998614 0.4931113 ]
  [0.10399414 0.61529674]
  [0.17895435 0.24070886]
  [0.60759435 0.87610231]]

 [[0.78614296 0.10129572]
  [0.49201303 0.14744193]
  [0.95573607 0.904298  ]
  [0.38560813 0.33493505]]

 [[0.71501197 0.94756549]
  [0.81000085 0.32938859]
  [0.160998   0.98811681]
  [0.34828328 0.7511219 ]]]


In [11]:
array_3d2 = np.random.randint(0, 10, size=(3, 4, 2))

In [12]:
print(array_3d2)

[[[3 3]
  [4 4]
  [2 1]
  [0 4]]

 [[1 7]
  [1 5]
  [9 4]
  [8 1]]

 [[0 5]
  [5 3]
  [8 1]
  [6 6]]]
